name: Python package

on:
  push:
    branches:
      - master
  schedule:
    - cron: 00 02 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requeirments.txt
      - name: execute py script
        env:
          JUEJIN_USERNAME: ${{ secrets.JUEJIN_USERNAME }}
          JUEJIN_PASSWORD: ${{ secrets.JUEJIN_PASSWORD }}
          JUEJIN_NICKNAME: ${{ secrets.JUEJIN_NICKNAME }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          SWITCH: ${{ secrets.SWITCH }}
          PUBLISH_SWITCH: ${{ secrets.PUBLISH_SWITCH }}

        run: |
          python main.py