name: Python package

on:
  push:
    branches:
      - master
  schedule:
    - cron: 00 00 * * *

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
#       - name: Set up chromedriver
#         uses: nanasess/setup-chromedriver@master
#         with:
#             # Optional: do not specify to match Chrome's version
#             chromedriver-version: '88.0.4324.96'
      
#       - name: Set up chrome
#         uses: browser-actions/setup-chrome@latest
#         with:
#             chrome-version: 94.0.4606.71
        
      - name: Install chrome version
        run: |
          sudo apt-get install wget
          sudo apt-get install unzip
          LATEST=$(google-chrome --product-version)102.0.5005.61
          echo $LATEST
          sudo wget "https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver 
          sudo mv chromedriver /usr/bin/
          
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requeirments.txt
      - name: execute py script
        env:
          JUEJIN_USERNAME: ${{ secrets.JUEJIN_USERNAME }}
          JUEJIN_PASSWORD: ${{ secrets.JUEJIN_PASSWORD }}
          JUEJIN_NICKNAME: ${{ secrets.JUEJIN_NICKNAME }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          SWITCH: ${{ secrets.SWITCH }}
          PUBLISH_SWITCH: ${{ secrets.PUBLISH_SWITCH }}

        run: |
          python main.py
